AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Cadastra uma nova fila
Resources:
  createqueue:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: Cadastra uma nova fila
      MemorySize: 128
      Timeout: 3
      Role: ''
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 10
        Api1:
          Type: Api
          Properties:
            Path: /queue
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - 
        SubnetIds:
          - 
      Environment:
        Variables:
          MAXIMUM_QTD_NAME: '128'
          MAXIMUM_QTD_TEXT: '2000'
      Layers:
        - ''
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}
